apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: sporhund-purring
  namespace: tbd
  labels:
    team: tbd
    dbPolicyUser: purring
spec:
  schedule: "0 0 * * *"
  timeZone: "Europe/Oslo"
  command:
    - /usr/bin/java
    - -cp
    - /app/resources:/app/classes:/app/libs/*
    - no.nav.helse.sporhund.PurringJobKt
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  envFrom:
    - secret: google-sql-sporhund-sporhund-purring-494b7001
  env:
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "sporhund"
