apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sporhund
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  startup:
    path: isready
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 9
  liveness:
    path: isalive
  readiness:
    path: isready
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 640Mi
    requests:
      cpu: 20m
      memory: 512Mi
  replicas:
    min: 2
    max: 3
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
#        extra:
#          - "NAVident"
#        groups:
#          - id: {{ENTRAID_UUID_KODE_7_DEV}}
#          - id: {{ENTRAID_UUID_SPEIL_BESLUTTERE_DEV}}
#          - id: {{ENTRAID_UUID_SPEIL_SAKSBEHANDLER_DEV}}
#          - id: {{ENTRAID_UUID_SPEIL_STIKKPROVE_DEV}}
#          - id: {{ENTRAID_UUID_SPEIL_LESETILGANG_DEV}}
  accessPolicy:
    inbound:
      rules:
        - application: speil
          cluster: dev-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-custom-1-3840
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
        databases:
          - name: sporhund
            envVarPrefix: DATABASE
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sporhund-v1
