apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: sporhund-purring
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  schedule: "0 0 * * *"
  timeZone: "Europe/Oslo"
  command:
    - /usr/bin/java
    - -cp
    - /app/*
    - no.nav.helse.sporhund.PurringJobKt
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 128Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: sporhund
            envVarPrefix: DATABASE

